openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'invento'
servers:
  - url: 'localhost:8081'
paths:
    /user:
        get:
            parameters:
                - in: query
                  name: all
                  required: true
                  schema:
                      type: boolean
                - in: query
                  name: id
                  required: false
                  schema:
                      type: boolean
            responses:
                '200':
                    description: 'get users'
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object

                