openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'invento'
servers:
  - url: 'localhost:8081'
paths:
    /user:
        get:
            parameters:
                - in: query
                  name: all
                  required: true
                  schema:
                      type: boolean
                - in: query
                  name: id
                  required: false
                  schema:
                      type: string
            responses:
                '200':
                    description: 'get users'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/users'
components:
    schemas:
        users:
            type: array
            items:
                type: object
                properties:
                    name:
                        type: string
                    email:
                        type: string
                    phone:
                        type: number
                    role:
                        type: string
                    pass:
                        type: string
                 